In [3]:
import pandas as pd

df = pd.read_csv('./2018~2020추정매출금액.csv')

In [16]:
display(df)

,기준년,기준분기코드,상권구분코드,상권구분코드명,상권코드,상권코드명,서비스업종코드,서비스업종코드명,당월매출금액,당월매출건수,...,20대매출금액,30대매출금액,40대매출금액,50대매출금액,60대이상매출금액,주중매출건수,주말매출건수,남성매출건수,여성매출건수,점포수
0,2018,1,D,발달상권,1001046,서울 관악구 신림역_4,CS200036,고시원,83495157,281,...,0,37037037,38888889,0,7569231,281,0,281,0,0
1,2018,1,D,발달상권,1001025,서울 관악구 서울대입구역_1,CS200012,법무사사무소,6571318,116,...,773096,5798222,0,0,0,116,0,77,39,10
2,2018,1,A,골목상권,1000289,인촌로17가길,CS300021,문구,6044732,23,...,0,0,431767,999880,4613085,23,0,23,0,4
3,2018,1,A,골목상권,1000515,남부순환로70길,CS200030,피부관리실,11863957,40,...,0,0,4491978,4971979,0,40,0,0,36,1
4,2018,1,A,골목상권,1000902,논현로63길,CS200029,네일숍,1766586,19,...,0,730195,0,0,68650,16,3,0,15,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430560,2020,1,A,골목상권,1000380,동일로192길,CS200008,한의원,80240216,2149,...,1822018,5214777,16203198,48892424,8107799,1810,339,1176,973,3
430561,2020,1,A,골목상권,1000380,동일로192길,CS200016,당구장,45644291,3317,...,15887301,6779439,3822724,14220017,3924182,2075,1242,3015,302,4
430562,2020,1,A,골목상권,1000175,답십리로64길,CS100007,치킨전문점,124879476,7088,...,25257045,31881474,32729508,19458716,10545372,4802,2286,3552,3350,5
430563,2020,1,A,골목상권,1000380,동일로192길,CS200024,스포츠클럽,9930070,23,...,5654624,0,4275447,0,0,23,0,14,10,4
430564,2020,1,A,골목상권,1000380,동일로192길,CS200025,자동차수리,5543854,111,...,380839,896658,1909014,1518533,544744,82,29,72,29,1

In [28]:
import pandas as pd


# 최초 43만
# CS100001,한식음식점
# CS100004,양식음식점
# CS100002,중식음식점
# CS100003,일식음식점
# CS100006,패스트푸드점
# CS100007,치킨전문점
# 서비스업종코드,서비스업종코드명


df = pd.read_csv('./2018~2020추정매출금액.csv') # 실제 파일 경로
# continent 컬럼을 선택합니다.
# 컬럼의 값과 조건을 비교합니다.
# 그 결과를 새로운 변수에 할당합니다.

is_korea = df['서비스업종코드'] == 'CS100001'
is_eu = df['서비스업종코드'] == 'CS100004'
is_china = df['서비스업종코드'] == 'CS100002'
is_japan = df['서비스업종코드'] == 'CS100003'
is_ff = df['서비스업종코드'] == 'CS100006'
is_ck = df['서비스업종코드'] == 'CS100007'



subset_df = df[is_korea | is_eu | is_china | is_japan|is_ff|is_ck]
subset_df.to_csv('./6food.csv',encoding='cp949') # 파일 저장할 경로 및 파일 이름

In [24]:
display(subset_df)

,기준년,기준분기코드,상권구분코드,상권구분코드명,상권코드,상권코드명,서비스업종코드,서비스업종코드명,당월매출금액,당월매출건수,...,20대매출금액,30대매출금액,40대매출금액,50대매출금액,60대이상매출금액,주중매출건수,주말매출건수,남성매출건수,여성매출건수,점포수
7,2018,1,A,골목상권,1001001,천중로39길,CS100007,치킨전문점,176770341,7113,...,26950272,43746668,52049475,29842243,10191248,4852,2261,3976,2912,3
10,2018,1,D,발달상권,1001122,여의도 시범아파트앞,CS100004,양식음식점,250726281,11935,...,18059412,43544123,38381515,17306802,15190719,11595,340,4079,4346,3
13,2018,1,A,골목상권,1000852,논현로27길,CS100007,치킨전문점,64702023,2834,...,11853165,16575292,13598346,9081926,2936806,1885,949,1561,992,2
14,2018,1,A,골목상권,1000306,창경궁로43길,CS100003,일식음식점,263199309,8278,...,29567586,46529479,55874146,44000323,28217902,5673,2605,3162,3721,1
16,2018,1,A,골목상권,1000846,강남대로8길,CS100006,패스트푸드점,152999635,13787,...,30193685,41201342,29570825,12493660,3998886,10450,3337,6907,5192,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430540,2020,1,A,골목상권,1000380,동일로192길,CS100006,패스트푸드점,212635079,17345,...,69551546,36288438,41636585,30906319,9029008,12349,4996,7972,8857,9
430541,2020,1,A,골목상권,1000380,동일로192길,CS100007,치킨전문점,352055825,14541,...,121580989,62859787,76777052,65491796,14906568,9621,4920,9126,5306,5
430554,2020,1,A,골목상권,1000175,답십리로64길,CS100001,한식음식점,538829577,22665,...,38785590,89979563,119439249,152468397,90116909,17917,4748,13850,6512,28
430556,2020,1,A,골목상권,1000073,청파로47길,CS100001,한식음식점,1767817259,84644,...,702889216,337118183,233377650,177806751,64059361,66061,18583,26859,53235,45
430562,2020,1,A,골목상권,1000175,답십리로64길,CS100007,치킨전문점,124879476,7088,...,25257045,31881474,32729508,19458716,10545372,4802,2286,3552,3350,5

기준년
기준분기코드
상권구분코드
상권구분코드명
상권코드
상권코드명
서비스업종코드
서비스업종코드명
당월매출금액
당월매출건수
주중매출금액
주말매출금액
남성매출금액
여성매출금액
10대매출금액
20대매출금액
30대매출금액
40대매출금액
50대매출금액
60대이상매출금액
주중매출건수
주말매출건수
남성매출건수
여성매출건수
점포수